dist: trusty
branches:
  only:
  - master
node_js:
- 6.9.4
install:
- npm install -g backslide
- npm install --prefix talk/html_output mathjax
- pip install ghp-import
script:
- cd talk && bs export -l -r -o html_output && mv html_output/presentation.html html_output/index.html
- cp template/remark.min.js html_output/
- cp -r template/img html_output/ && cd ..
after_script:
- ghp-import -m "Publish slides" -b gh-pages talk/html_output
- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} gh-pages
env:
  global:
  - secure: "IXHlgV9iIfURKU2cBQPoFhBVjV3bC7r956kCvzT6WQEUqZlqNKvIKHeSnMStai3ZR1alSGuPdSvXA01XC+JLUGeSK9/E7pz2+eZl5axbSa/WICel+sSaNGETqzgR4Ob5W2H5aDeTD4+/SmXrY5dhe65FqPWmghFdPkHnZEb/jOlYYUvwXbK/kKgEj3GBJjombIqpx5w+vtnXcf99aZWhkAln7dB4FsR949yIurar6Z4GHF3X+FX9nKdQuTTvhBNzRMjc3AEBEtGWOzLYZfbMG7c7TFF8cAK2C7l6ACDCtbQrgO6X1ljNVISbwmhvBHENoFo+2eEHizG3BY+1zjV2ezZuRKURC9xO3TmOF6f8iAuPto7nfho5LW5h+jJT02YZ24xdMGIbA3GXj9jscgYDOU6zaZkmEa6JIxZwDIstHAtB2vHTn//cdvFwD9jg5zMCmJk+oQN1X2Ge/dycKo5jtdm5enaMBK/2TAxYmZU5HWyE0sAfKjV+PVKrMDtwsWMA1oK1Sz/UnVX0jiXEsPwVaLTymG8nsvdr4irvSMkOCo5P1Z32YVOsZWJxjhQAZC5+HAssmtY9T02JtiE1K/0qo24qWeIsKnUFOeRzH8eLWJH9qi+bHPD9x30+LAsMTPTQIAcpuzpow+TR0VYusK32mOgkE+UqeT/97rCQlAaWdr0="